### ISSUE TITLE
Travis failing with Pochoir

### ISSUE THREAD

**Issue by ggorman** [opesci/propagator#13]

**Comment by marcoscimatec** [comment]
We found that one of the issues is that travis limits resources to virtual machines. If a process run for more than 10 minutes without doing any output it's killed. If it uses to much memory and many threads, it's killed as well.
One of the solutions was to separate the CTest calls, and put the "travis_wait" before it, so it waits longer for the process to finish.
Another point was to change the "#!/bin/sh" to "#!/bin/bash" on the pochoir_compile script. This was preventing cp from working, and the code could not be compiled by pochoir.

**Comment by ggorman** [comment]
Thanks for the patch @felippezacarias
